apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: python
  labels:
    app: python
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: arjunachari12
        image: arjunachari12/my-python-image
        ports:
        - name: python
          containerPort: 3000
